### ISSUE TITLE
KSP Blockers Tracking

### ISSUE THREAD

**Issue by ZacSweers** [ZacSweers/anvil#16]
Tracking issue for known KSP/Dagger issues

- [ ] https://github.com/google/ksp/issues/1676 (soft blocker, affects KMP projects)
- [ ] https://github.com/google/dagger/issues/4356 (related to the above, but Dagger needs to do their own resolution too)
- [ ] https://github.com/google/dagger/issues/4505

---

**Resolved**
- [x] https://github.com/google/ksp/issues/2091 (hard blocker on KSP2)
- [x] https://github.com/google/ksp/issues/2088 (hard blocker on KSP2)
- [x] https://github.com/google/ksp/issues/1956 (hard blocker on KSP2)
- [x] https://github.com/google/ksp/issues/1966 (hard blocker on KSP2)
  - Possibly fixed in Kotlin 2.1.0-beta
- [x] https://github.com/google/dagger/issues/4376 (soft blocker on KSP2, only affects annotations with enum properties)
- [x] https://github.com/square/kotlinpoet/pull/1956 (soft blocker, only affects typealiased scope annotations)
- [x] https://youtrack.jetbrains.com/issue/KT-49235 (1000 superinterfaces limit in kotlin, only affects huge codebases)
  - Will be fixed in 2.1.0-beta1
- [x] https://github.com/google/ksp/issues/1883 (hard blocker on KSP2 if you use repeated annotations)
- [x] https://github.com/google/ksp/issues/1854

**Comment by ZacSweers** [comment]
#94
